version: '3.8'

services:
  backend:
    build:
      context: ./las_backend
      dockerfile: Dockerfile
    container_name: las-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - las_db_data:/app/data
    environment:
      # Use an environment variable for the DB path to store it in the mounted volume
      - DATABASE_FILE=./data/las.db

  frontend:
    build:
      context: ./las_frontend
      dockerfile: Dockerfile
    container_name: las-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  las_db_data:
